### ISSUE TITLE
Enhance firmware structure with more support

### ISSUE THREAD

**Issue by ciotlosm** [Koenkk/zigbee2mqtt-firmware#8]
I thought it's best to raise an issue here than to bloat already long threads. This is just ask if @ptvoinfo @kirovilya and @oskarn97 would be willing to contribute their firmware for common structured storage. Of course this would be just a nice to have and it's by no means a "pressure" request!

I've tried to update documentation here to help structure things and I'd be happy to put more documentation around various types of firmware produced. I know some firmwares are not compiled from source, but just patched hex files and this would be useful if we could also document on how the compilation / modification process was achieved.

**Comment by oskarn97** [comment]
I've added the sources I used to compile my firmware with 48 devices.

**Comment by ptvoinfo** [comment]
Can we add ZStack sources here? Did someone read the TI license agreement fully?

**Comment by ciotlosm** [comment]
@ptvoinfo you might be right. I haven't read it as I don't have the software - incompatible platform. 

> https://e2e.ti.com/support/wireless_connectivity/w/design_notes/copyright-c-for-z-stack-and-timac

Would hex files be still ok to upload? Would be good to have at least those.

**Comment by ciotlosm** [comment]
@ptvoinfo makes sense. Would at least diffs from defaults be allowed?

@Koenkk maybe extract "tools" in a personal repo and add the disclaimer around TI licence and prohibited countries?

**Comment by ptvoinfo** [comment]
@ciotlosm I'm not a lawyer :) and cannot guarantee that my opinion is correct. We may look at similar big projects and borrow their experience.

**Comment by Koenkk** [comment]
To avoid any problems:

- Create a new repo: https://github.com/Koenkk/Z-Stack-firmware
- In that repo, add firmware files and instructions on how to modify and build
- Remove this repo
